"""Writes a Jupyter notebook that re-runs the QA for a fileset step by step."""

from pathlib import Path

import nbformat
from nbformat.v4 import new_code_cell, new_markdown_cell, new_notebook

from sbe_qa_processing.qa import QAResult


def build_notebook(result: QAResult, output_dir: Path) -> nbformat.NotebookNode:
    config = result.config
    identifier = config.identifier
    config_path = Path(result.config_path).resolve() if result.config_path else None
    cells = [
        new_markdown_cell(
            f"# SBE 9/911plus QA: {config.cruise_id} fileset {config.fileset_id}\n\n"
            f"{config.cruise_name}\n\n"
            "Re-runs the quality assessment behind this fileset's PDF report and R2R QA XML: "
            "it reads each cast's raw `.hex` with its `.XMLCON`, converts it with "
            "[seabirdscientific](https://github.com/Sea-BirdScientific/seabirdscientific), runs "
            "R2R's CTD tests and the science checks, and writes the reports. Edit the paths or "
            "the cruise config's `[thresholds]` and re-run to change the assessment.\n\n"
            f"Generated by sbe-qa-processing {result.versions['sbe-qa-processing']} with "
            f"seabirdscientific {result.versions['seabirdscientific']}."
        ),
        new_code_cell(
            "from pathlib import Path\n\n"
            "# Inputs and outputs\n"
            f"CONFIG = Path({str(config_path)!r})\n"
            f"FILESET = Path({str(result.fileset.root.resolve())!r})\n"
            f"OUTPUT_DIR = Path({str(output_dir.resolve())!r})"
        ),
        new_code_cell(
            "%matplotlib inline\n"
            "import warnings\n\n"
            "import matplotlib.pyplot as plt\n"
            "import pandas as pd\n"
            "from IPython.display import display\n\n"
            "from sbe_qa_processing import plots\n"
            "from sbe_qa_processing.pdf_report import write_pdf\n"
            "from sbe_qa_processing.qa import run_qa\n"
            "from sbe_qa_processing.xml_report import write_qa_xml\n\n"
            "# seabirdscientific's EOS-80 module imports the deprecated seawater package\n"
            'warnings.filterwarnings("ignore", "The seawater library is deprecated")\n'
            'pd.set_option("display.max_colwidth", 120)\n\n'
            "result = run_qa(CONFIG, FILESET)\n"
            'print(f"{len(result.casts)} casts read; R2R rating {result.r2r.rating}")'
        ),
        new_markdown_cell(
            "## R2R certificate\n\n"
            "The tests and infos written to the R2R QA 2.0 XML. Deck tests (file names with "
            "deck/dock/test) are left out of the NAV tests, as R2R does."
        ),
        new_code_cell(
            "display(pd.DataFrame([\n"
            '    {"test": t.name, "rating": t.rating, "result": t.result, "passed": t.passed,\n'
            '     "total": t.total, "failures": ", ".join(t.failures)}\n'
            "    for t in result.r2r.tests\n"
            "]))\n"
            'display(pd.DataFrame([{"info": i.name, "value": i.value} for i in result.r2r.infos]))'
        ),
        new_code_cell(
            "figure = plots.cast_map(result.casts, result.config)\n"
            "display(figure)\n"
            "plt.close(figure)"
        ),
        new_markdown_cell(
            "## Science checks\n\n"
            "Dual-sensor agreement, plausible ranges, Wild Edit spikes, lost scans, NMEA position, "
            "pump status and cast behavior for each converted cast that isn't a deck test."
        ),
        new_code_cell(
            "checks = pd.DataFrame([\n"
            '    {"cast": cast, "check": c.name, "status": c.status, "value": c.value,\n'
            '     "limit": c.limit, "detail": c.detail}\n'
            "    for cast, results in result.science.items()\n"
            "    for c in results\n"
            "])\n"
            'display(checks.pivot(index="check", columns="cast", values="status")'
            '.reindex(checks["check"].unique()))\n'
            'display(checks[checks["status"].isin(["warn", "fail"])])'
        ),
        new_markdown_cell(
            "## Sensor loadout\n\n"
            "The sensor on each channel of every cast, from its `.XMLCON`, with calibration age "
            "at the time of the cast."
        ),
        new_code_cell(
            "from sbe_qa_processing.loadout import cast_loadout, instrument_settings\n\n"
            "for data in result.science_casts:\n"
            "    print(data.name, '-', instrument_settings(data))\n"
            "    display(pd.DataFrame([vars(row) for row in cast_loadout(data)])"
            '.drop(columns="calibration_text"))'
        ),
        new_markdown_cell(
            "## Bottle fires\n\n"
            "From each cast's `.bl` bottle log; pressure is the mean over the scans logged for "
            "each fire. Casts without bottle fires are skipped."
        ),
        new_code_cell(
            "from sbe_qa_processing.bottles import bottle_fires\n\n"
            "for data in result.science_casts:\n"
            "    fires = bottle_fires(data)\n"
            "    if fires:\n"
            "        print(f'{data.name}: {len(fires)} bottles')\n"
            "        display(pd.DataFrame([vars(fire) for fire in fires]))"
        ),
        new_markdown_cell("## Casts"),
        new_code_cell(
            "for data in result.science_casts:\n"
            "    for make in (plots.profiles, plots.ts_diagram, plots.pressure_series):\n"
            "        figure = make(data)\n"
            "        display(figure)\n"
            "        plt.close(figure)"
        ),
        new_markdown_cell("## Write the reports"),
        new_code_cell(
            "OUTPUT_DIR.mkdir(parents=True, exist_ok=True)\n"
            f'xml_path = write_qa_xml(result, OUTPUT_DIR / "{identifier}_qa.2.0.xml")\n'
            f'pdf_path = write_pdf(result, OUTPUT_DIR / "{identifier}_qa_report.pdf")\n'
            "print(xml_path)\n"
            "print(pdf_path)"
        ),
    ]
    notebook = new_notebook(cells=cells)
    notebook.metadata["kernelspec"] = {
        "name": "python3",
        "display_name": "Python 3",
        "language": "python",
    }
    notebook.metadata["language_info"] = {"name": "python"}
    return notebook


def write_notebook(
    result: QAResult, path: Path | str, output_dir: Path | str, execute: bool = False
) -> Path:
    path = Path(path)
    notebook = build_notebook(result, Path(output_dir))
    if execute:
        try:
            from nbclient import NotebookClient
        except ImportError as error:
            raise RuntimeError("executing the notebook needs nbclient and ipykernel") from error
        NotebookClient(
            notebook, timeout=1800, resources={"metadata": {"path": str(path.parent)}}
        ).execute()
    nbformat.write(notebook, path)
    return path
